# language: android
# dist: trusty
# jdk: oraclejdk8

# env:  
#   global:
#     - ANDROID_TARGET=android-22
#     - ANDROID_ABI=armeabi-v7a
# android:
#   update_sdk: true
#   components:
#     # Uncomment the lines below if you want to
#     # use the latest revision of Android SDK Tools
#     - tools
#     - platform-tools
   

#     # The BuildTools version used by your project
#     - build-tools-29.0.3

#     # The SDK version used to compile your project
#     - android-29
#     - android-22

#     # Additional components
#     - extra-google-google_play_services
#     - extra-google-m2repository
#     - extra-android-m2repository

#     # Specify at least one system image,
#     # if you need to run emuldist: trusty
#     - sys-img-x86-android-29
#     - sys-img-armeabi-v7a-android-22

# # Emulator Management: Create, Start and Wait
# #before_script:
# script:
# #   - ./gradlew build jacocoTestReport assembleAndroidTest
#   - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 100M
#   - emulator -avd test -no-audio -no-window &
#   - android-wait-for-emulator
#   - adb shell input keyevent 82 &
#   - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
#   - ./gradlew clean createDebugCoverageReport jacocoTestReport
#   - ./gradlew connectedCheck
 
# after_success:
#   - bash <(curl -s https://codecov.io/bash)  
  
# # Avoiding cache  
#   before_cache:
#   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
# cache:
#   directories:
#     - $HOME/.gradle/caches/
#     - $HOME/.gradle/wrapper/
#     - $HOME/.android/build-cache

sudo: false
language: android

# before_cache:
# - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
# - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - ANDROID_TARGET=android-22
  - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools #
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - add-on
  - extra
  - $ANDROID_TARGET
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
licenses:
- 'android-sdk-preview-license-52d11cd2'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'
script:
- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --device 'Nexus 4' --sdcard 128M
- emulator -avd test -no-window -skin 768x1280 &
- android-wait-for-emulator
- adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
- ./gradlew clean createDebugCoverageReport jacocoTestReport

branches:
  only:
  - master
after_success:
- bash <(curl -s https://codecov.io/bash)

