codecov:
  require_ci_to_pass: yes

#coverage:
#  precision: 2
#  round: down
#  range: "0...100"
#  status:
#    project:
#      users:
#        paths: "C:\Users\FORRTY\Videos\Sprint @\Software-Design-master\app\src\androidTest\java\com\example\marketplace\classes\UserTest.java"

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "tests/"  # only include coverage in "tests/" folder
      app:  # declare a new status context "app"
        paths: "!tests/"  # remove all files in "tests/"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
